volumes:
  psql_data:
    driver: local
services:
  postgres:
    image: postgres:alpine
    container_name: psql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./app/lib:/docker-entrypoint-initdb.d
      - psql_data:/var/lib/postgresql/data
  reply_radar:
    container_name: web
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: ["sh", "-c", "corepack enable && pnpm dev"]
    ports:
      - "3000:3000"
